New API
Alzymologist/Kalatori-backend pull request #31
Opened 2024-04-01 06:35 UTC by fluiderson

2024-04-01 15:24 UTC, kirushik requested changes

2024-04-01 15:24 UTC, kirushik commented on src/server.rs
> +                kind: TokenKind::Assets,
This yields `assets` instead of a singular `asset`, which violates the API defined in https://alzymologist.github.io/kalatori-api/

2024-04-01 15:24 UTC, kirushik commented on src/server.rs
> +        Ok((order_status, order_success)) => match order_success {
This doesn't work as specified in the API docs.
It **should** return the full details about the current status of the order (including amount, currency info etc), while the only thing I'm getting is

```json
{
    "message": "",
    "order": "123456",
    "payment_status": "unknown",
    "recipient": "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
    "server_info": {
        "debug": true,
        "instance_id": "",
        "version": "0.2.0-rc1"
    }
}
```

2024-04-02 00:02 UTC, fluiderson commented on src/main.rs
> +    let rpc = env::var("KALATORI_RPC").unwrap();
I added it just for this mockup to process a single RPC endpoint. It won't be in the final version, all RPC endpoints will be obtained only from the config.

2024-09-24 20:56 UTC, closed without merging